config/routes.rb
Rails.application.routes.draw do
  get 'conversations/create'

  get 'conversations/show'

  devise_for :users

  resources :users do
    resources :projects
  end

  resources :projects do
    resources :notes
  end

  resources :conversations do
    resources :messages
  end

  resources :events

  authenticated :user do
    root 'users#show', as: :authenticated_root
  end

  root 'landing#index'

  get 'landing/about'

  get 'landing/contact'

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :project
  validates :title, presence: true
  validates :body, presence: true

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  before_action :find_note, only: [:show, :edit, :update, :destroy]

  def index
    @notes = Note.all
  end

  def new
    @project = Project.find(params[:project_id])
    @note = current_user.notes.build
  end

  def create
    @project = Project.find(params[:project_id])
    @note = @project.notes.build(note_params)
    @note.save ? flash[:notice] = "Note created." : flash[:error] = "Note could not be created, please try again."
    redirect_to [current_user, @project]
  end

  def show
  end

  def edit
  end

  def update
    if @note.update_attributes(note_params)
      @note.save
      flash[:notice] = "Note updated."
      redirect_to [current_user, @project] 
    else
      flash[:error] = "Could not update note."
      render :edit
    end
  end

  def destroy
    @note.delete ? flash[:notice] = "Note deleted." : flash[:error] = "Note could not be deleted."
    redirect_to [current_user, @project]
  end

  private

  def note_params
    params.require(:note).permit(:title, :body)
  end

  def find_note
    @project = Project.find(params[:project_id])
    @note = @project.notes.find(params[:id])
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for [@project, @note] do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="action">
    <%= f.submit "Save Note", class: "btn btn-success" %>
  </div>
<% end %>

app/views/notes/_note.html.erb
<%= div_for(note) do %>
  <li>
    <%= note.title %>
  </li>
  <li>
    <%= note.body %>
  </li>
<% end %>

app/views/notes/create.js.erb
$('.notes').prepend("<%= j render(@note) %>");
$('#note_title, #note_body').val('');

app/views/notes/edit.html.erb
      <div id="instructions" class="col-sm-9 paper">
          <%= form_for [@project, @note] do |f| %>

            <div class="form-group">
              <%= f.label :title %>
              <%= f.text_field :title, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= f.label :notes %>
              <%= f.text_area :body, rows: 10, class: "form-control" %>
            </div>

            <div class="action">
              <%= f.submit "Save Note", class: "btn btn-success" %>
            </div>
          <% end %>
        <br>
        <%= link_to "Delete Note", project_note_path, method: :delete, class: "btn btn-danger", data: {confirm: "Are you sure?"} %>
      </div>
  </div>
</div>