config/routes.rb
Rails.application.routes.draw do
  get 'conversations/create'

  get 'conversations/show'

  devise_for :users

  resources :users do
    resources :projects
  end

  resources :projects do
    resources :notes
  end

  resources :conversations do
    resources :messages
  end

  resources :events

  authenticated :user do
    root 'users#show', as: :authenticated_root
  end

  root 'landing#index'

  get 'landing/about'

  get 'landing/contact'

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :notes
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :find_project, only: [:update, :destroy, :edit]
  
  def index
    @projects = current_user.projects
  end

  def new
    @project = Project.new
  end

  def create
    @project = current_user.projects.build(project_params)
      if @project.save
        flash[:notice] = "Project saved."
        redirect_to user_project_path(current_user, @project)
      else
        flash[:error] = "Could not save project, please try again."
        render :new 
      end
  end

  def update
      if @project.update_attributes(project_params)
        @project.save
        redirect_to user_project_path
      else
        flash[:error] = "Could not update project title, please try again."
      end
  end

  def edit
  end

  def show
    @project = Project.find(params[:id])
    @notes = @project.notes.select(&:persisted?)
    @note = @project.notes.build
  end

  def destroy
      if @project.delete
        redirect_to authenticated_root_path 
      else
        flash[:error] = "Could not delete project, please try again."
      end
  end

  private

  def project_params
    params.require(:project).permit(:title)
  end

  def find_project
    @project = current_user.projects.find(params[:id])
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/index.html.erb
<div class="row">
  <div class="col-md-2 user-nav">
  <span class="avatar">
    <%= image_tag current_user.avatar.url(:thumb) %>
  </span>
    <%= link_to current_user.name, authenticated_root_path %><br>
    <a href="#"><i class="fa fa-circle text-success"></i> Online</a>  <!-- Add conditional online/offline code -->
    <br><br><br>
    <ul>
      <li>
        <%= link_to "  Projects", user_projects_path, class: "fa fa-folder-o" %>
      </li>
      <li>
        <%= link_to "  Notes", '#', class: "fa fa-newspaper-o"  %>
      </li>
      <li>
        <%= link_to "  Calendar", '#', class: "fa fa-calendar"  %>        
      </li>
      <li>
        <%= link_to "  Chat", '#', class: "fa fa-weixin"  %>        
      </li>
    </ul>
    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
  </div>
  <div class="col-md-10">
    <% current_user.projects.each do |project| %>
        <ul>
          <li>
            <%= link_to project.title, [current_user, project] %>
          </li>
        </ul>
    <% end %>
    <%= link_to "New Project", new_project_path, class: "btn btn-primary" %>

  </div>
</div>

app/views/projects/new.html.erb
<div class="container col-sm-9">
<h1>Create A New Project</h1>

<%= form_for @project do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="action">
    <%= f.submit "Save Title", class: "btn btn-success" %>
  </div>
<% end %>
</div>

app/views/projects/show.html.erb
  <div class="container">
    <div class="col-sm-9">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h1><%= @project.title %></h1>
          </div>
        <div class="panel-body">
          <p>Notes:</p>
          <% @notes.each do |note| %>
            <p><%= link_to note.title, edit_project_note_path(@project, note) %></p>
          <% end %>
        </div>
      </div>
      <%= link_to "Delete Project", user_project_path, method: :delete, class: "btn btn-danger", data: {confirm: "Are you sure?"} %>

      <h1>New Note</h1>

      <%= form_for [@project, @note] do |f| %>

        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :body %>
          <%= f.text_area :body, rows: 10, class: "form-control" %>
        </div>

        <div class="action">
          <%= f.submit "Save Note", class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
  </div>
</div>